### ISSUE TITLE
Problem with Gigamon IPFIX

### ISSUE THREAD

**Issue by zzurashvili** [logstash-plugins/logstash-codec-netflow#104]
I had logstash 5.2 getting netflow v9 successfully from gigamon but after I started exporting IPFix logstash started crashing as soon as It sees template. then I upgraded logstash to logstash-5.6.3 but issues remains.
This is what I'm getting
[2017-10-19T15:51:34,307][WARN ][logstash.codecs.netflow ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:34,330][WARN ][logstash.codecs.netflow ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:34,333][WARN ][logstash.codecs.netflow ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:34,668][WARN ][logstash.codecs.netflow ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:35,002][WARN ][logstash.codecs.netflow ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:35,121][ERROR][logstash.pipeline ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method >' for nil:NilClass", "backtrace"=>["(eval):1043:ininitialize'", "org/jruby/RubyArray.java:1613:in each'", "(eval):1035:ininitialize'", "org/jruby/RubyProc.java:281:in call'", "(eval):896:infilter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:inworker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}

looking at tcpdump I see that at 15:51:35 is when logstash got template.
this is my configuration file:
input {
udp {
port => 9996
codec => netflow {
versions => [9, 10]
target => ipfix
}
type => ipfix
receive_buffer_bytes => 16777216
queue_size=> 8000
}
}
filter ....

I'm sending ipfix flows from gigamon. again when I had in v9 format everything was working fine.
did anybody have the same issue and found solution?

**Comment by andrewvc** [comment]
@zzurashvili do you have a clean way to replicate this? Is there a way you could record the netflow data and make a reproducible test case?

**Comment by zzurashvili** [comment]
yes, I can easily replicate this. I'm attaching PCAP file (full data capture)
[ipfix.zip](https://github.com/logstash-plugins/logstash-codec-netflow/files/1422638/ipfix.zip)
 which shows all data coming on logstash collector. As soon it sees template (seq number 5 in pcap file) it crashes.

**Comment by jorritfolmer** [comment]
Thanks for the pcap, I'll take a look.
Somewhere next week though.

**Comment by jorritfolmer** [comment]
I'm not able to reproduce the issue with the pcap.
It decodes both template and following data packets fine.
Tried:

- logstash 5.5.0 with logstash-netflow-codec 3.7.0
- logstash 5.6.4 with logstash-codec-netflow 3.7.0 (most recent out-of-the-box)

How many gigamon devices are you exporting from?
Are they all the same version? There are issues with devices sharing the same template id but with slightly different contents, maybe this is a symptom of that?

**Comment by zzurashvili** [comment]
Thanks for checking.
I'm using logstash 5.6.0 and logstash-codec-netflow 3.5.2 (I thought this was the newest one, could the be a problem?)
I'm exporting from 2 devices and they are both the same version. 
I will test what happens when I start exporting from only 1.

**Comment by zzurashvili** [comment]
I installed  logstash-codec-netflow-3.8.0 and started exporting from only one Gigamon device but issue remains. 
[2017-11-15T08:43:55,073][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 286 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-11-15T08:43:55,814][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `>' for nil:NilClass", "backtrace"=>["(eval):1043:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1035:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):896:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2017-11-15T08:43:55,882][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `>' for nil:NilClass>, :backtrace=>["(eval):1043:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1035:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):896:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}

**Comment by zzurashvili** [comment]
removed old codecs completly, restarted logstash and started working.
thanks for the help

**Comment by jorritfolmer** [comment]
Good to hear, thanks for the update!
