### ISSUE TITLE
Exception in inputworker... revisited.

### ISSUE THREAD

**Issue by robcowart** [logstash-plugins/logstash-codec-netflow#134]
Logstash 6.2.4
logstash-codec-netflow-3.12.0
Ubuntu 16.04 LTS
JDK 1.8.0_161-b12

Back in September I opened #90 which @andrewvc fixed with 62e5bfddcf7f271c118a606d2df062a20d5c28fc

I have recently been working with a couple of customers who have high volumes of IPFIX data, and these issues are reappearing.

When I look at the code it appears that the changes made by @andrewvc were made only to the `decode_netflow9` method, and not `decode_ipfix`.

In particular I am looking at...

line 249-254 from decode_netflow9:
```
template = @decode_mutex_netflow.synchronize { @netflow_templates[key] }

if !template
  @logger.warn("Can't (yet) decode flowset id #{record.flowset_id} from source id #{flowset.source_id}, because no template to decode it with has been received. This message will usually go away after 1 minute.")
  return events
end
```
lines 347-352 from decode_ipfix: (this is the way Netflow was before @andrewvc changes.)
```
if @ipfix_templates[key] != nil
  template = @ipfix_templates[key]
else
  @logger.warn("Can't (yet) decode flowset id #{record.flowset_id} from observation domain id #{flowset.observation_domain_id}, because no template to decode it with has been received. This message will usually go away after 1 minute.")
  return events
end
```
This section of code is also referenced in the backtrace (see below). I am guessing that changing this section of code in `decode_ipfix` to function as it now does in `decode_netflow9` will fix this problem. Ruby isn't really my language so I wanted to point this out so that it can be confirmed and implemented by the experts.

For completeness here are examples of the errors I am seeing in the logs:
```
[2018-04-27T22:57:47,252][ERROR][logstash.inputs.udp      ]
Exception in inputworker {
  "exception"=>#<NoMethodError: undefined method `unpack' for nil:NilClass>,
  "backtrace"=>[
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.12.0/lib/logstash/codecs/netflow/util.rb:63:in `get'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/primitive.rb:112:in `sensible_default'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/base_primitive.rb:147:in `_value'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/base_primitive.rb:86:in `snapshot'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/struct.rb:109:in `block in snapshot'",
    "org/jruby/RubyArray.java:1734:in `each'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/struct.rb:107:in `snapshot'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/base.rb:234:in `=='",
    "uri:classloader:/jruby/kernel/basicobject.rb:4:in `!='",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.12.0/lib/logstash/codecs/netflow.rb:347:in `decode_ipfix'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.12.0/lib/logstash/codecs/netflow.rb:131:in `block in decode'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/array.rb:208:in `block in each'",
    "org/jruby/RubyArray.java:1734:in `each'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/array.rb:208:in `each'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.12.0/lib/logstash/codecs/netflow.rb:130:in `decode'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.3.2/lib/logstash/inputs/udp.rb:142:in `inputworker'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.3.2/lib/logstash/inputs/udp.rb:111:in `block in udp_listener'"
  ]
}

[2018-04-27T23:25:36,111][ERROR][logstash.inputs.udp      ]
Exception in inputworker {
  "exception"=>#<NoMethodError: undefined method `has_parameter?' for nil:NilClass>,
  "backtrace"=>[
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/struct.rb:267:in `include_obj?'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/struct.rb:109:in `block in snapshot'",
    "org/jruby/RubyArray.java:1734:in `each'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/struct.rb:107:in `snapshot'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/base.rb:234:in `=='",
    "uri:classloader:/jruby/kernel/basicobject.rb:4:in `!='",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.12.0/lib/logstash/codecs/netflow.rb:347:in `decode_ipfix'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.12.0/lib/logstash/codecs/netflow.rb:131:in `block in decode'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/array.rb:208:in `block in each'",
    "org/jruby/RubyArray.java:1734:in `each'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/array.rb:208:in `each'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.12.0/lib/logstash/codecs/netflow.rb:130:in `decode'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.3.2/lib/logstash/inputs/udp.rb:142:in `inputworker'",
    "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.3.2/lib/logstash/inputs/udp.rb:111:in `block in udp_listener'"
  ]
}
```

**Comment by jorritfolmer** [comment]
Ah yes good catch!

**Comment by jorritfolmer** [comment]
I'm adding ipfix_stress.py in a later commit.
It reproduces this issue within 2 minutes.
After applying your PR it hasn't crashed in 10 minutes.

**Comment by robcowart** [comment]
Good to hear!

I have been spending a lot of time lately trying to maximize throughput for UDP/flow use-cases. I explained some of my recommendations [here](https://discuss.elastic.co/t/only-get-900-netflow-events-sec-from-4-vcpu-ls-node/129928/2?u=rcowart). As these changes improved the capacity to ingest more UDP packets the problem shifted to the input worker exceptions. That's really no surprise since the worker exceptions are triggered by higher load. With this fix I am optimistic that I am very near to an optimized and stable setup.

Thanks.

**Comment by robcowart** [comment]
Just an update. I have also applied the change at a customer who was experiencing these issues and they have had no problems for almost 24 hours. So it appears the issues are indeed fixed.
