### ISSUE TITLE
netflow codec crashes with NoMethodError: undefined method `elements' for "0.0.0.0":IP4Addr

### ISSUE THREAD

**Issue by sysmonk** [logstash-plugins/logstash-codec-netflow#47]
Hi,

Our logstash stopped parsing netflows a couple times in the last week. Both times the error was:
`NoMethodError: undefined method `elements' for "0.0.0.0":IP4Addr`
Full error:

```
{:timestamp=>"2016-09-05T01:50:07.929000+0000", :message=>"Exception in inputworker", "exception"=>#<NoMethodError: undefined method `elements' for "0.0.0.0":IP4Addr>, "backtrace"=>["org/jruby/RubyBasicObject.java:1555:in `method_missing'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base_primitive.rb:106:in `method_missing'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/primitive.rb:84:in `method_missing'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/array.rb:329:in `do_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/struct.rb:134:in `do_read'", "org/jruby/RubyArray.java:1613:in `each'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/struct.rb:134:in `do_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/array.rb:329:in `do_read'", "org/jruby/RubyArray.java:1613:in `each'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/array.rb:329:in `do_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/struct.rb:134:in `do_read'", "org/jruby/RubyArray.java:1613:in `each'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/struct.rb:134:in `do_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base.rb:147:in `read'", "org/jruby/RubyProc.java:281:in `call'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base.rb:253:in `start_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base.rb:145:in `read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base.rb:21:in `read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.5/lib/logstash/codecs/netflow.rb:79:in `decode'", "/home/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:96:in `inputworker'", "/home/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:73:in `udp_listener'"], :level=>:error}
{:timestamp=>"2016-09-05T01:50:07.929000+0000", :message=>"Exception in inputworker", "exception"=>#<NoMethodError: undefined method `elements' for "0.0.0.0":IP4Addr>, "backtrace"=>["org/jruby/RubyBasicObject.java:1555:in `method_missing'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base_primitive.rb:106:in `method_missing'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/primitive.rb:84:in `method_missing'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/array.rb:329:in `do_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/struct.rb:134:in `do_read'", "org/jruby/RubyArray.java:1613:in `each'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/struct.rb:134:in `do_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/array.rb:329:in `do_read'", "org/jruby/RubyArray.java:1613:in `each'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/array.rb:329:in `do_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/struct.rb:134:in `do_read'", "org/jruby/RubyArray.java:1613:in `each'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/struct.rb:134:in `do_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base.rb:147:in `read'", "org/jruby/RubyProc.java:281:in `call'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base.rb:253:in `start_read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base.rb:145:in `read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.3.0/lib/bindata/base.rb:21:in `read'", "/home/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-2.0.5/lib/logstash/codecs/netflow.rb:79:in `decode'", "/home/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:96:in `inputworker'", "/home/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:73:in `udp_listener'"], :level=>:error}
```

Logstash 2.3.1 on Debian Jessie 
The config file is huge, but assuming that it dies at udp listener / codec decode, the related config part is simple:

```
input {
        udp {
                port => 5556
                codec => netflow {
                        versions => [5]
                }
                type => "netflow"
        }
}
```

I don't know what packets it was processing at that time and can't provide a tcpdump.

**Comment by jorritfolmer** [comment]
Thanks for the report. This seems to originate somewhere in the BinData gem we use, because the netflow codec doesn't use any `elements` method.

I'll have to look into it further, later.

**Comment by jorritfolmer** [comment]
I've been trying to reproduce it with Netflow v5 packets that contain 0.0.0.0 as ipv4_dst_addr, ipv4_src_addr and ipv4_next_hop, just in case. However, these don't seem to be causing the exceptions you're getting.

**Comment by jorritfolmer** [comment]
Hi @sysmonk is this still going on?
Unfortunately I'm unable to reproduce it, and have no idea where to look.
Some questions then:

- what version Bindata gem are you using
- what version Logstash-codec-netflow gem are you using
