### ISSUE TITLE
When the plugin tries to save the IPFIX (netflow v10) it fails if it doesn't have the proper permissions

### ISSUE THREAD

**Issue by jeremyforan** [logstash-plugins/logstash-codec-netflow#80]
Everything seems to be working fine until the first template comes in and it seems to crash.  I suspect it may be an issue with the permissions of the file.  I have changed the permission of the template file to "chmod 777" and it seems to have resolved the issue.  It may be beneficial to add a permissions check on the file to ensure this doesn't happen during production.

- Version:
      Logstash 5.4.1
- Operating System:
     AWS AMI  Linux 4.9.27-14.31.amzn1.x86_64 #1 SMP Wed May 10 01:58:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Config File:
```
   input{
  udp {
    port => "4739"
    receive_buffer_bytes => 26214400
    queue_size => 2000
    codec => netflow {
      versions => [10]
      target => "ipfix"
      ipfix_definitions => "/etc/logstash/ipfix-elements.yaml"
      cache_save_path => "/tmp"
   }
   type => ipfix
  }
}
```
- Sample Error:
```
[2017-07-11T12:35:52,061][ERROR][logstash.inputs.udp	  ] Exception in inputworker {"exception"=>#<RuntimeError: LogStash::Codecs::Netflow: saving templates cache file failed (/tmp/ipfix_templates.cache) with error Permission denied - /
tmp/ipfix_templates.cache>, "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-3.4.0/lib/logstash/codecs/netflow.rb:506:in `save_templates_cache'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logs
tash-codec-netflow-3.4.0/lib/logstash/codecs/netflow.rb:407:in `decode_ipfix'", "org/jruby/RubyKernel.java:1242:in `catch'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-3.4.0/lib/logstash/codecs/netflow.rb:387
:in `decode_ipfix'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `each'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/binda
ta/array.rb:208:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-3.4.0/lib/logstash/codecs/netflow.rb:386:in `decode_ipfix'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-3.4
.0/lib/logstash/codecs/netflow.rb:207:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `each'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1
.9/gems/bindata-2.4.0/lib/bindata/array.rb:208:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-netflow-3.4.0/lib/logstash/codecs/netflow.rb:206:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/l
ogstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:118:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:89:in `udp_listener'"]}
```

**Comment by jorritfolmer** [comment]
Thanks for the suggestion to add a permissions check!
