### ISSUE TITLE
Template length doesn't fit cleanly into flowset AND No matching template for flow id 257

### ISSUE THREAD

**Issue by Devorkin** [logstash-plugins/logstash-codec-netflow#86]
- Version:  Logstash 5.5.1/logstash-codec-netflow (3.4.1)
- Operating System: CentOS Linux release 7.3.1611
- Device which gathering Netflow data from: Fortigate 100D
- Device software version: FortiOS 5.4.2
- Device Netflow version: 9
- Config
`input {
        udp {
                port    =>      9995
                codec   =>      netflow
                tags    =>      "netflow"
        }
}

filter {
        translate {
                exact           =>      true
                field           =>      "[netflow][protocol]"
                destination     =>      "[netflow][protocol_name]"
                dictionary_path => "/etc/logstash/filters/translate/protocol_dict.yaml"
        }
        translate {
                exact           =>      true
                field           =>      "[netflow][l4_dst_port]"
                destination     =>      "[netflow][destination_port]"
                dictionary_path => "/etc/logstash/filters/translate/logstash-iana-services-dictionary.yaml"
        }
}

output {
        if "netflow" in [tags] {
                elasticsearch {
                index   =>      "logstash_netflow-%{+YYYY.MM.dd}"
                        hosts   =>      ["localhost:9200"]
                }
        }
}`

- Sample:
[2017-08-03T14:29:26,420][DEBUG][logstash.codecs.netflow  ] Start processing data flowset 257
[2017-08-03T14:29:26,421][WARN ][logstash.codecs.netflow  ] No matching template for flow id 257
...
[2017-08-03T14:29:26,421][DEBUG][logstash.codecs.netflow  ] Start processing data flowset 262
[2017-08-03T14:29:26,421][WARN ][logstash.codecs.netflow  ] Template length doesn't fit cleanly into flowset {:template_id=>262, :template_length=>69, :record_length=>76}
...
[2017-08-03T14:29:27,609][DEBUG][logstash.codecs.netflow  ] Start processing data flowset 262
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Start processing template
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint64, :in_bytes]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint64, :out_bytes]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint32, :in_pkts]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint32, :out_pkts]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint32, :first_switched]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint32, :last_switched]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint16, :l4_src_port]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint16, :l4_dst_port]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint16, :input_snmp]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint16, :output_snmp]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint8, :protocol]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:application_id, :application_id]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:skip, nil, {:length=>2}]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:forwarding_status, :forwarding_status]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:uint8, :flow_end_reason]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:ip4_addr, :ipv4_src_addr]}
[2017-08-03T14:29:27,610][DEBUG][logstash.codecs.netflow  ] Field definition complete for template 258 {:field=>[:ip4_addr, :ipv4_dst_addr]}
[2017-08-03T14:29:27,612][DEBUG][logstash.codecs.netflow  ] Received template 258 with fields [[:uint64, :in_bytes], [:uint64, :out_bytes], [:uint32, :in_pkts], [:uint32, :out_pkts], [:uint32, :first_switched], [:uint32, :last_switched], [:uint16, :l4_src_port], [:uint16, :l4_dst_port], [:uint16, :input_snmp], [:uint16, :output_snmp], [:uint8, :protocol], [:application_id, :application_id], [:skip, nil, {:length=>2}], [:forwarding_status, :forwarding_status], [:uint8, :flow_end_reason], [:ip4_addr, :ipv4_src_addr], [:ip4_addr, :ipv4_dst_addr]]
[2017-08-03T14:29:27,614][DEBUG][logstash.codecs.netflow  ] Received template 258 of size 62 bytes. Representing in 57 BinData bytes
[2017-08-03T14:29:27,614][WARN ][logstash.codecs.netflow  ] Template length doesn't fit cleanly into flowset {:template_id=>262, :template_length=>69, :record_length=>76}
...

- Steps to Reproduce:
Start Logstash
View the logs
Receive the above warnings repeatedly

Using Wireshark with a Pcap file from TCPdump and decode as CFlow I was able to see the needed data I'm looking for (SRC\DST ips, etc...); But Logstash cannot.

I would like to know if this plugin will be able to handle this kind of Netflow data or not.
If I can help investigate or troubleshoot it, please let me know how and I will do my best!

*Also sent the Pcap to your (@jorritfolmer) email, as did it already in the past

Thanks.

**Comment by jorritfolmer** [comment]
Ok found it: the application_id field (95) is treated as a fixed_size of 4 bytes by the codec, whereas the Cisco doc specifies it as a non-fixed 1+N bytes field. 

You can try this quick and dirty fix, I'll look into a more durable solution:

```diff
diff --git a/lib/logstash/codecs/netflow/util.rb b/lib/logstash/codecs/netflow/util.rb
index 3cf23fb..97b81ac 100644
--- a/lib/logstash/codecs/netflow/util.rb
+++ b/lib/logstash/codecs/netflow/util.rb
@@ -111,11 +111,11 @@ end
 class Application_Id < BinData::Primitive
   endian :big
   uint8  :classification_id
-  uint24 :selector_id
+  uint64 :selector_id
 
   def set(val)
-    self.classification_id=val.to_i<<24
-    self.selector_id = val.to_i-((val.to_i>>24)<<24)
+    self.classification_id=val.to_i<<64
+    self.selector_id = val.to_i-((val.to_i>>64)<<64)
   end
 
   def get
```

**Comment by jorritfolmer** [comment]
Did this quick fix work?

**Comment by h-schwanbeck** [comment]
The patch worked for me, thanks a lot!

**Comment by h-schwanbeck** [comment]
Hello again,

worked perfectly fine yesterday, but since 02:00am my ES log fills with a constant stream of stack traces.

org.elasticsearch.index.mapper.MapperParsingException: failed to parse [netflow.application_id]
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:298) ~[elasticsearch-5.6.0.jar:5.6.0]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:468) ~[elasticsearch-5.6.0.jar:5.6.0]
...
Caused by: java.lang.NumberFormatException: For input string: "20:53068615909376"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:?]
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_141]
...

**Comment by jorritfolmer** [comment]
It appears ES expects application_id to be a number, when in fact is is a string "20:53068615909376". There's probably some mapping in ES you can set to correct this.

**Comment by jorritfolmer** [comment]
@Devorkin I'll be releasing v3.6.0 later today that fixes the Fortigate issue.
